package com.practica02.base.models;

public enum RolArtistaEnum {
    SOLISTA, VOCALISTA, BAJISTA, GUITARRISTA,
    DRUMMER, TECLADISTA, SAXOFONISTA, PIANISTA, 
    VIOLINISTA, TRUMPETISTA, TROMBONISTA, 
    PERCUSIONISTA, BAJO_SEXTO, ACORDEONISTA, 
    CLARINETISTA, FLAUTISTA, CHELISTA, OBOEISTA, 
    FISICISTAS;
    
}
